---
- name: Restart telegraf
  systemd:
    name: telegraf
    state: restarted

- name: Restart zookeeper
  systemd:
    name: zookeeper
    state: restarted

- name: Restart kafka
  systemd:
    name: kafka
    state: restarted

- name: Daemon reload
  systemd:
    daemon_reload: yes

